server:
  port: 8083

spring:
  # 数据库
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mail?characterEncoding=utf-8&serverTimezone=GMT%2B8
    # java -cp jasypt-1.9.2.jar org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI input="root" password=salt algorithm=PBEWithMD5AndDES
    # username: root
    username: ENC(kCrVeq8KkcXLHW/bhF/FSw==)
    # java -cp jasypt-1.9.2.jar org.jasypt.intf.cli.JasyptPBEStringEncryptionCLI input="root" password=salt algorithm=PBEWithMD5AndDES
    # password: root
    password: ENC(3KpiVCBiVKGfzIaKG+aMHQ==)
    # 启动的环境变量  -Djasypt.encryptor.password=salt
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    # 163
    # host: smtp.163.com
    # QQ
    host: smtp.qq.com
    # 用户名
    username: 1191026928@qq.com
    # 昵称
    nickname: 测试
    # 密码是QQ邮箱开启SMTP的授权码
    password: huvqsymqyorqjdce
    # 默认编码格式
    default-encoding: utf-8
    # 协议
    protocol: smtp
    # 端口号
    port: 25
    properties:
      mail:
        smtp:
          # 设置是否需要认证，如果为true,那么用户名和密码就必须的，
          # 如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的。
          auth: true
          # starttls是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。
          starttls:
            enable: true
            request: true
          # 连接时间限制
          connectiontimeout: 5000
          # 邮件接收时间限制
          timeout: 5000
          # 邮件发送时间限制
          writetimeout: 5000
  #thymeleaf模板配置
  thymeleaf:
    # 存放模板的文件夹，以resource文件夹为相对路径
    prefix: classpath:/templates/
    # 设置模板后缀名，默认为ftl
    suffix: .html
    # 设置页面编码格式
    encoding: utf-8
    # 设置文档类型
    content-type: text/html
    # 设置页面缓存
    cache: false
  #freemarker模板配置
  freemarker:
    # 存放模板的文件夹，以resource文件夹为相对路径
    template-loader-path: classpath:/templates/
    # 设置模板后缀名，默认为ftl
    suffix: .html
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false

mybatis:
  # 存放Mapper文件，以resource文件夹为相对路径
  mapper-locations: classpath:/mappers/*Mapper.xml
  # 驼峰命名
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  params: count=countSql
  reasonable: false
  supportMethodsArguments: true

jasypt:
  encryptor:
    password: salt
    algorithm: PBEWithMD5AndDES


